import { useRouter } from "expo-router";
import { useEffect, useState } from "react";
import { Alert, Pressable, ScrollView, Text, TextInput, View } from "react-native";

import type { AllFacts, BriefFacts, Flag } from "../src/types";
import { openDb } from "../src/services/store/db";
import { getAllFacts, getOpenFlags } from "../src/services/store/repos";
import { buildBriefFacts, postBrief } from "../src/services/share/BriefBuilder";
import QRCode from "react-native-qrcode-svg";

const PATIENT_ID = 1;

function VitalCard({
  label,
  value,
  sub,
  trend,
}: {
  label: string;
  value: string;
  sub?: string;
  trend?: string;
}) {
  return (
    <View className="flex-1 rounded-xl border border-clinical-outline-var bg-clinical-card p-4">
      <Text className="text-[11px] font-bold uppercase tracking-widest text-clinical-muted">
        {label}
      </Text>
      <Text className="mt-2 text-2xl font-bold text-clinical-fg">{value}</Text>
      {sub && <Text className="text-xs text-clinical-muted">{sub}</Text>}
      {trend && (
        <Text className="mt-1 text-xs font-medium text-clinical-secondary">{trend}</Text>
      )}
    </View>
  );
}

function DiscussPoint({ title, detail }: { title: string; detail: string }) {
  const [checked, setChecked] = useState(false);
  return (
    <Pressable
      onPress={() => setChecked(!checked)}
      className="flex-row items-start gap-3 py-2.5"
    >
      <View
        className={`mt-0.5 h-5 w-5 items-center justify-center rounded-full border ${
          checked ? "border-emerald-500 bg-emerald-500" : "border-clinical-primary"
        }`}
      >
        {checked && <Text className="text-[10px] text-white">✓</Text>}
      </View>
      <View className="flex-1">
        <Text
          className={`text-sm font-medium ${
            checked
              ? "text-clinical-muted line-through"
              : "text-clinical-fg"
          }`}
        >
          {title}
        </Text>
        <Text className="mt-0.5 text-xs text-clinical-muted">{detail}</Text>
      </View>
    </Pressable>
  );
}

export default function Share() {
  const [facts, setFacts] = useState<AllFacts | null>(null);
  const [flags, setFlags] = useState<Flag[]>([]);
  const [url, setUrl] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [briefData, setBriefData] = useState<BriefFacts | null>(null);
  const router = useRouter();

  useEffect(() => {
    (async () => {
      const db = await openDb();
      const [f, fl] = await Promise.all([
        getAllFacts(db, PATIENT_ID),
        getOpenFlags(db, PATIENT_ID),
      ]);
      setFacts(f);
      setFlags(fl);
      setBriefData(buildBriefFacts(f));
    })();
  }, []);

  async function generate() {
    if (!facts) return;
    setBusy(true);
    try {
      const payload = buildBriefFacts(facts);
      const res = await postBrief(payload);
      setUrl(res.url);
    } catch (e: any) {
      Alert.alert("Couldn't generate brief", e.message ?? String(e));
    } finally {
      setBusy(false);
    }
  }

  if (!facts || !briefData) {
    return (
      <View className="flex-1 items-center justify-center bg-clinical-surface">
        <Text className="text-sm text-clinical-muted">Loading...</Text>
      </View>
    );
  }

  const lastVisit = facts.encounters[0];
  const age = new Date().getFullYear() - parseInt(facts.patient.dob.slice(0, 4));

  return (
    <ScrollView className="flex-1 bg-clinical-surface" showsVerticalScrollIndicator={false}>
      {/* Header */}
      <View className="flex-row items-center gap-3 px-4 pt-14">
        <Pressable
          onPress={() => router.back()}
          className="h-10 w-10 items-center justify-center rounded-full bg-clinical-surface-mid"
        >
          <Text className="text-lg text-clinical-primary">←</Text>
        </Pressable>
        <Text className="text-xl font-bold text-clinical-primary">Visit Briefing</Text>
        <View className="ml-auto flex-row items-center gap-1.5 rounded-full bg-clinical-surface-low px-3 py-1">
          <View className="h-2 w-2 rounded-full bg-emerald-500" />
          <Text className="text-[11px] font-bold uppercase tracking-widest text-clinical-muted-variant">
            Ready
          </Text>
        </View>
      </View>

      {/* Title Section */}
      <View className="px-5 pt-5">
        <Text className="text-[11px] font-bold uppercase tracking-widest text-clinical-primary">
          GENERATED BY MEDOS AI
        </Text>
        <Text className="mt-1 text-3xl font-bold text-clinical-fg">Doctor Briefing</Text>
        <Text className="mt-1 text-sm text-clinical-muted">
          Summary of patient activity and vitals since last consultation
          {lastVisit ? ` on ${lastVisit.date}` : ""}.
        </Text>
      </View>

      {/* Clinical Summary */}
      <View className="mx-4 mt-5 overflow-hidden rounded-xl border border-clinical-outline-var bg-clinical-card">
        <View className="absolute left-0 top-0 h-full w-1 bg-clinical-primary" />
        <View className="p-5 pl-6">
          <View className="flex-row items-center gap-2">
            <Text className="text-base">📋</Text>
            <Text className="text-lg font-semibold text-clinical-fg">Clinical Summary</Text>
          </View>
          <Text className="mt-3 text-sm leading-6 text-clinical-fg">
            {briefData.patient.name}, {age}y {briefData.patient.sex}. Active conditions:{" "}
            {briefData.conditions.map((c) => c.name).join(", ") || "None"}.{" "}
            Currently on {briefData.medications.filter((m) => m.active).length} active
            medication(s).
          </Text>
          {flags.length > 0 && (
            <View className="mt-3 flex-row flex-wrap gap-2">
              {flags.slice(0, 3).map((f) => (
                <View
                  key={f.id}
                  className="flex-row items-center gap-1 rounded bg-clinical-error-bg px-2 py-1"
                >
                  <Text className="text-xs">⚠</Text>
                  <Text className="text-[11px] font-bold uppercase text-clinical-error">
                    {f.subject}
                  </Text>
                </View>
              ))}
            </View>
          )}
        </View>
      </View>

      {/* Vitals */}
      <View className="mx-4 mt-4 flex-row gap-3">
        <VitalCard
          label="RESTING HR"
          value={`${facts.wearable?.[0]?.restingHr ?? 72}`}
          sub="BPM"
        />
        <VitalCard
          label="ACTIVE MEDS"
          value={`${briefData.medications.filter((m) => m.active).length}`}
          sub="Prescriptions"
        />
      </View>

      {/* Key Points to Discuss */}
      <View className="mx-4 mt-5 rounded-xl border border-clinical-outline-var bg-clinical-card p-5">
        <View className="flex-row items-center gap-2">
          <Text className="text-base">✅</Text>
          <Text className="text-lg font-semibold text-clinical-fg">Key Points to Discuss</Text>
        </View>
        <View className="mt-3">
          {briefData.follow_ups.map((fu, i) => (
            <DiscussPoint key={i} title={fu.test} detail={fu.reason} />
          ))}
          {briefData.watch_list.map((w, i) => (
            <DiscussPoint key={`w-${i}`} title={w} detail="Flagged for review" />
          ))}
          {briefData.follow_ups.length === 0 && briefData.watch_list.length === 0 && (
            <Text className="text-sm text-clinical-muted">
              No specific discussion points generated yet.
            </Text>
          )}
        </View>
      </View>

      {/* QR / Share Section */}
      <View className="mx-4 mb-8 mt-5 rounded-xl border border-clinical-primary bg-clinical-primary p-5">
        {!url ? (
          <View className="items-center">
            <Text className="text-[11px] font-bold uppercase tracking-widest text-blue-200">
              SHARE WITH YOUR DOCTOR
            </Text>
            <Text className="mt-2 text-center text-sm text-blue-100">
              Generate a secure, temporary briefing link that your doctor can scan or open.
            </Text>
            <Pressable
              onPress={generate}
              disabled={busy}
              className={`mt-4 w-full items-center rounded-xl py-3.5 ${
                busy ? "bg-white/50" : "bg-white"
              }`}
            >
              <Text className="text-sm font-bold text-clinical-primary">
                {busy ? "Building Brief..." : "Generate & Share"}
              </Text>
            </Pressable>
          </View>
        ) : (
          <View className="items-center">
            <View className="rounded-2xl bg-white p-4">
              <QRCode value={url} size={180} />
            </View>
            <Text className="mt-3 text-center text-sm font-semibold text-white">
              Show this QR code to your doctor
            </Text>
            <TextInput
              value={url}
              editable={false}
              selectTextOnFocus
              className="mt-2 w-full rounded-lg bg-white/20 p-2.5 text-center text-xs text-white"
            />
            <Text className="mt-1 text-xs text-blue-200">Expires in 24 hours</Text>
            <Pressable
              onPress={() => setUrl(null)}
              className="mt-3 rounded-lg border border-white/30 px-5 py-2"
            >
              <Text className="text-sm font-semibold text-white">Regenerate</Text>
            </Pressable>
          </View>
        )}
      </View>
    </ScrollView>
  );
}
